package labr_client.GUI.forms;

import java.io.File;
import java.io.InputStream;
import java.net.URL;
import javax.swing.JFileChooser;

/**
 *
 * @author labbl
 */
public class FileChooser extends javax.swing.JFrame {

    /**
     * Creates new form FileChooser
     */
    public FileChooser(boolean dir) {
        initComponents();
        if (dir) {
            jFileChooser1.setFileSelectionMode(jFileChooser1.FILES_AND_DIRECTORIES);
        } else {
            jFileChooser1.setFileSelectionMode(jFileChooser1.FILES_ONLY);
        }

    }

    public String returnChoice(String path) {
        path = path.replace("\\", "/");
        File f2 = new File(path);

        if (!f2.exists()) {
            ClassLoader classLoader = ClassLoader.getSystemClassLoader();
            URL location = classLoader.getResource(path);
            f2 = new File(location.getPath());
        }

        jFileChooser1.setCurrentDirectory(f2);

        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser1.getSelectedFile();
            // if the user accidently click a file, then select the parent directory.
            if (!f.isDirectory() & jFileChooser1.getFileSelectionMode() == jFileChooser1.FILES_AND_DIRECTORIES) {
                f = f.getParentFile();
            }
            return f.getPath();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
